In [1]:
# Library to suppress warnings or deprecation notes 
import warnings
warnings.filterwarnings('ignore')

# Libraries to help with reading and manipulating data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Libraries to help with data visualization
%matplotlib inline
import sys
from PIL import Image
%matplotlib inline

In [2]:
df=pd.read_csv(('studentVle.csv'))

In [3]:
df.shape

(10655280, 6)

In [4]:
df.head()

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [5]:
df.tail()

         code_module code_presentation  id_student  id_site  date  sum_click
10655275         GGG             2014J      675811   896943   269          3
10655276         GGG             2014J      675578   896943   269          1
10655277         GGG             2014J      654064   896943   269          3
10655278         GGG             2014J      654064   896939   269          1
10655279         GGG             2014J      654064   896939   269          1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   code_module        object
 1   code_presentation  object
 2   id_student         int64
 3   id_site            int64
 4   date               int64
 5   sum_click          int64
dtypes: int64(4), object(2)
memory usage: 487.8+ MB

In [7]:
df.isnull().sum()

code_module          0
code_presentation    0
id_student           0
id_site              0
date                 0
sum_click            0
dtype: int64

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id_student,10655280.0,733333.566872,582705.982511,6516.0,507743.0,588236.0,646484.0,2698588.0
id_site,10655280.0,738323.416400,131219.622162,526721.0,673519.0,730069.0,877030.0,1049562.0
date,10655280.0,95.174000,76.071301,-25.0,25.0,86.0,156.0,269.0
sum_click,10655280.0,3.716946,8.849047,1.0,1.0,2.0,3.0,6977.0

In [9]:
df.mode()

  code_module code_presentation  id_student  id_site  date  sum_click
0         FFF             2014J      537811   882537    18          1

In [10]:
df.nunique()

code_module              7
code_presentation        4
id_student           26074
id_site               6268
date                   295
sum_click              498
dtype: int64

In [11]:
df.head()

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [12]:
#create unique identifier for each id_site and student in the course run

df = df.astype({'id_site':'string'})
df["code_module_site_presentation"]=df[['code_module','code_presentation','id_site']].agg('-'.join,axis=1)
df = df.astype({'id_student':'string'})
df["code_module_student_presentation"]=df[['code_module','code_presentation','id_student']].agg('-'.join,axis=1)
df.head()

,code_module,code_presentation,id_student,id_site,date,sum_click,code_module_site_presentation,code_module_student_presentation
0,AAA,2013J,28400,546652,-10,4,AAA-2013J-546652,AAA-2013J-28400
1,AAA,2013J,28400,546652,-10,1,AAA-2013J-546652,AAA-2013J-28400
2,AAA,2013J,28400,546652,-10,1,AAA-2013J-546652,AAA-2013J-28400
3,AAA,2013J,28400,546614,-10,11,AAA-2013J-546614,AAA-2013J-28400
4,AAA,2013J,28400,546714,-10,1,AAA-2013J-546714,AAA-2013J-28400

In [13]:
df.head()

,code_module,code_presentation,id_student,id_site,date,sum_click,code_module_site_presentation,code_module_student_presentation
0,AAA,2013J,28400,546652,-10,4,AAA-2013J-546652,AAA-2013J-28400
1,AAA,2013J,28400,546652,-10,1,AAA-2013J-546652,AAA-2013J-28400
2,AAA,2013J,28400,546652,-10,1,AAA-2013J-546652,AAA-2013J-28400
3,AAA,2013J,28400,546614,-10,11,AAA-2013J-546614,AAA-2013J-28400
4,AAA,2013J,28400,546714,-10,1,AAA-2013J-546714,AAA-2013J-28400

In [14]:
### Data Cleaning for text columns in the dataset. I will remove the special characters and numbers from the text columns in the dataset.
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].str.strip().str.lower()

In [15]:
df.head()

,code_module,code_presentation,id_student,id_site,date,sum_click,code_module_site_presentation,code_module_student_presentation
0,aaa,2013j,28400,546652,-10,4,aaa-2013j-546652,aaa-2013j-28400
1,aaa,2013j,28400,546652,-10,1,aaa-2013j-546652,aaa-2013j-28400
2,aaa,2013j,28400,546652,-10,1,aaa-2013j-546652,aaa-2013j-28400
3,aaa,2013j,28400,546614,-10,11,aaa-2013j-546614,aaa-2013j-28400
4,aaa,2013j,28400,546714,-10,1,aaa-2013j-546714,aaa-2013j-28400

#observations for studentVle dataset
# Total 6 columns 
#  2 columns objective type and 4 columns were int type data
# There is no null values
# checked unique values and based on model requirement we can change data type like 0bjective to int and vicevarsa.

In [16]:
#inspect the results after cleaning the text columns in the dataset.
for col in df.select_dtypes(include=['object']).columns:
    print(col)
    print(df[col].unique())
    print('_' * 40)

code_module
['aaa' 'bbb' 'ccc' 'ddd' 'eee' 'fff' 'ggg']
________________________________________
code_presentation
['2013j' '2014j' '2013b' '2014b']
________________________________________
code_module_site_presentation
['aaa-2013j-546652' 'aaa-2013j-546614' 'aaa-2013j-546714' ...
 'ggg-2014j-896948' 'ggg-2014j-896952' 'ggg-2014j-896969']
________________________________________
code_module_student_presentation
['aaa-2013j-28400' 'aaa-2013j-30268' 'aaa-2013j-31604' ...
 'ggg-2014j-650630' 'ggg-2014j-631446' 'ggg-2014j-624767']
________________________________________

In [17]:
df.shape

(10655280, 8)

In [18]:
df.head()

,code_module,code_presentation,id_student,id_site,date,sum_click,code_module_site_presentation,code_module_student_presentation
0,aaa,2013j,28400,546652,-10,4,aaa-2013j-546652,aaa-2013j-28400
1,aaa,2013j,28400,546652,-10,1,aaa-2013j-546652,aaa-2013j-28400
2,aaa,2013j,28400,546652,-10,1,aaa-2013j-546652,aaa-2013j-28400
3,aaa,2013j,28400,546614,-10,11,aaa-2013j-546614,aaa-2013j-28400
4,aaa,2013j,28400,546714,-10,1,aaa-2013j-546714,aaa-2013j-28400

In [19]:
df.tail()

,code_module,code_presentation,id_student,id_site,date,sum_click,code_module_site_presentation,code_module_student_presentation
10655275,ggg,2014j,675811,896943,269,3,ggg-2014j-896943,ggg-2014j-675811
10655276,ggg,2014j,675578,896943,269,1,ggg-2014j-896943,ggg-2014j-675578
10655277,ggg,2014j,654064,896943,269,3,ggg-2014j-896943,ggg-2014j-654064
10655278,ggg,2014j,654064,896939,269,1,ggg-2014j-896939,ggg-2014j-654064
10655279,ggg,2014j,654064,896939,269,1,ggg-2014j-896939,ggg-2014j-654064

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 8 columns):
 #   Column                            Dtype
---  ------                            -----
 0   code_module                       object
 1   code_presentation                 object
 2   id_student                        string
 3   id_site                           string
 4   date                              int64
 5   sum_click                         int64
 6   code_module_site_presentation     object
 7   code_module_student_presentation  object
dtypes: int64(2), object(4), string(2)
memory usage: 650.3+ MB

# Data cleaning done
# Data merging done.
# There is no missing values in entire dataset
# i can drop 3 columns as i merged code_modue,id_student and code_presentaion.
# code_module_student_presentation column will give accrate data with which module with presentation of course along with id_student.

In [21]:
### Drop columns that are not needed for a nalysis. 
df=df.drop(columns=['code_module','id_student','code_presentation'], axis=1)

In [22]:
#check the shape of the dataset after dropping the columns.
df.shape

(10655280, 5)

In [23]:
df.head()

,id_site,date,sum_click,code_module_site_presentation,code_module_student_presentation
0,546652,-10,4,aaa-2013j-546652,aaa-2013j-28400
1,546652,-10,1,aaa-2013j-546652,aaa-2013j-28400
2,546652,-10,1,aaa-2013j-546652,aaa-2013j-28400
3,546614,-10,11,aaa-2013j-546614,aaa-2013j-28400
4,546714,-10,1,aaa-2013j-546714,aaa-2013j-28400

### observations:
1.sum of the clicks useful to know student log in times and spending time on courses.
2.Number of clicks will give feed back bout student interest as he will continue course or dropped inbetween.
3.id_site will give feed back about which site is performing good.

In [24]:
# Loading the vle dataset to merge with studentVle dataset.
vle=pd.read_csv(('vle.csv'))

In [25]:
# check the shape of the vle dataset.
vle.shape

(6364, 6)

In [26]:
# check the head of the vle dataset.
vle.head()

   id_site code_module code_presentation activity_type  week_from  week_to
0   546943         AAA             2013J      resource        NaN      NaN
1   546712         AAA             2013J     oucontent        NaN      NaN
2   546998         AAA             2013J      resource        NaN      NaN
3   546888         AAA             2013J           url        NaN      NaN
4   547035         AAA             2013J      resource        NaN      NaN

In [27]:
#check the tail of the vle dataset.
vle.tail()

      id_site code_module code_presentation activity_type  week_from  week_to
6359   897063         GGG             2014J      resource        NaN      NaN
6360   897109         GGG             2014J      resource        NaN      NaN
6361   896965         GGG             2014J     oucontent        NaN      NaN
6362   897060         GGG             2014J      resource        NaN      NaN
6363   897100         GGG             2014J      resource        NaN      NaN

In [28]:
##check the info of the vle dataset.
vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6364 entries, 0 to 6363
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_site            6364 non-null   int64
 1   code_module        6364 non-null   object
 2   code_presentation  6364 non-null   object
 3   activity_type      6364 non-null   object
 4   week_from          1121 non-null   float64
 5   week_to            1121 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 298.4+ KB

In [29]:
##check the info of the null values in the vle dataset.
vle.isnull().sum()

id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

#Missing values replaced with zeros

In [30]:
for col in vle.select_dtypes(include=['object']).columns:
    print(col)
    print(vle[col].unique())
    print('_' * 40)

code_module
['AAA' 'BBB' 'CCC' 'DDD' 'EEE' 'FFF' 'GGG']
________________________________________
code_presentation
['2013J' '2014J' '2013B' '2014B']
________________________________________
activity_type
['resource' 'oucontent' 'url' 'homepage' 'subpage' 'glossary' 'forumng'
 'oucollaborate' 'dataplus' 'quiz' 'ouelluminate' 'sharedsubpage'
 'questionnaire' 'page' 'externalquiz' 'ouwiki' 'dualpane'
 'repeatactivity' 'folder' 'htmlactivity']
________________________________________

In [31]:
for col in vle.select_dtypes(include=['float64']).columns:
    print(col)
    print(vle[col].unique())
    print('_' * 40)

week_from
[nan  2.  1.  9. 11. 22.  6.  8. 19.  4. 15. 14. 25. 20. 27. 16. 24.  3.
 21. 18. 26. 10.  5. 28. 23. 13. 12.  7. 17.  0. 29.]
________________________________________
week_to
[nan  2.  1.  9. 11. 22.  6.  8. 19.  4. 15. 14. 25. 20. 27. 16. 24.  3.
 21. 18. 26. 10.  5. 28. 23. 13. 12.  7. 17.  0. 29.]
________________________________________

In [32]:
#check the mean,median and mode of the vle dataset.
vle.describe().T

,count,mean,std,min,25%,50%,75%,max
id_site,6364.0,726099.094123,128315.137473,526721.0,661592.75,730096.5,814016.25,1077905.0
week_from,1121.0,15.204282,8.792865,0.0,8.00,15.0,22.00,29.0
week_to,1121.0,15.214987,8.779806,0.0,8.00,15.0,22.00,29.0

In [33]:
#replace the null values in the vle dataset with 0.
# Based on 25% and 50% week from week to data ,we can replace missing values with Zero.
vle.fillna(0, inplace=True)

In [34]:
vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6364 entries, 0 to 6363
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_site            6364 non-null   int64
 1   code_module        6364 non-null   object
 2   code_presentation  6364 non-null   object
 3   activity_type      6364 non-null   object
 4   week_from          6364 non-null   float64
 5   week_to            6364 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 298.4+ KB

In [35]:
# confirmed that dataser filled missed values with zeros by checking info and head and tail
vle.head()

   id_site code_module code_presentation activity_type  week_from  week_to
0   546943         AAA             2013J      resource        0.0      0.0
1   546712         AAA             2013J     oucontent        0.0      0.0
2   546998         AAA             2013J      resource        0.0      0.0
3   546888         AAA             2013J           url        0.0      0.0
4   547035         AAA             2013J      resource        0.0      0.0

In [36]:
vle.tail()

      id_site code_module code_presentation activity_type  week_from  week_to
6359   897063         GGG             2014J      resource        0.0      0.0
6360   897109         GGG             2014J      resource        0.0      0.0
6361   896965         GGG             2014J     oucontent        0.0      0.0
6362   897060         GGG             2014J      resource        0.0      0.0
6363   897100         GGG             2014J      resource        0.0      0.0

In [37]:
# create unique identifier for each id_site in the course run 

vle = vle.astype({'id_site':'string'})
vle["code_module_site_presentation"]=vle[['code_module','code_presentation','id_site']].agg('-'.join,axis=1)
vle = vle.drop(columns=['code_module','code_presentation','id_site'])
vle.head()

  activity_type  week_from  week_to code_module_site_presentation
0      resource        0.0      0.0              AAA-2013J-546943
1     oucontent        0.0      0.0              AAA-2013J-546712
2      resource        0.0      0.0              AAA-2013J-546998
3           url        0.0      0.0              AAA-2013J-546888
4      resource        0.0      0.0              AAA-2013J-547035

In [38]:
### Data Cleaning for text columns in the dataset. I will remove the special characters and numbers from the text columns in the dataset.
for col in vle.select_dtypes(include=['object']).columns:
    vle[col] = vle[col].str.strip().str.lower()

In [39]:
#inspect the results after cleaning the text columns in the dataset.
for col in vle.select_dtypes(include=['object']).columns:
    print(col)
    print(vle[col].unique())
    print('_' * 40)

activity_type
['resource' 'oucontent' 'url' 'homepage' 'subpage' 'glossary' 'forumng'
 'oucollaborate' 'dataplus' 'quiz' 'ouelluminate' 'sharedsubpage'
 'questionnaire' 'page' 'externalquiz' 'ouwiki' 'dualpane'
 'repeatactivity' 'folder' 'htmlactivity']
________________________________________
code_module_site_presentation
['aaa-2013j-546943' 'aaa-2013j-546712' 'aaa-2013j-546998' ...
 'ggg-2014j-896965' 'ggg-2014j-897060' 'ggg-2014j-897100']
________________________________________

In [40]:
# merge data into vle dataframe

vle = vle.merge(df,on="code_module_site_presentation", how="outer")
print(vle.shape)
vle.head()

(10655376, 8)

,activity_type,week_from,week_to,code_module_site_presentation,id_site,date,sum_click,code_module_student_presentation
0,homepage,0.0,0.0,aaa-2013j-546614,546614,-10.0,11.0,aaa-2013j-28400
1,homepage,0.0,0.0,aaa-2013j-546614,546614,-10.0,3.0,aaa-2013j-30268
2,homepage,0.0,0.0,aaa-2013j-546614,546614,-10.0,11.0,aaa-2013j-31604
3,homepage,0.0,0.0,aaa-2013j-546614,546614,-10.0,13.0,aaa-2013j-32885
4,homepage,0.0,0.0,aaa-2013j-546614,546614,-10.0,13.0,aaa-2013j-38053